routes/web.php
<?php

use App\Http\Controllers\Dash\Todo;
use App\Helpers\AuthenticationHelper;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\Register;
use App\Http\Controllers\Dash\Dashboard;
use App\Http\Controllers\Auth\Authenticate;
use App\Http\Controllers\Auth\ChangePassword;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => null, 'middleware' => ['prevent-back-history'], 'as' => 'web.'], function () {
    Route::match(['get', 'head'], null, [Dashboard::class, 'index'])->middleware(['auth', 'verified:web.account.notverified'])->name('index');

    Route::resource('todos', Todo::class, ['middleware' => ['auth', 'verified:web.account.notverified'], 'as' => null])->parameters([
        'todos' => 'id',
    ])->scoped(['id' => 'uuid']);

    Route::group(['prefix' => 'account', 'middleware' => [], 'as' => 'account.'], function () {
        Route::match(['get', 'head'], 'register', [Register::class, 'viewRegister'])->middleware(['guest'])->name('register');

        Route::match(['post'], 'register', [Register::class, 'store'])->middleware(['guest'])->name('register');

        Route::match(['get', 'head'], 'login', [Authenticate::class, 'viewLogin'])->middleware(['guest'])->name('login');

        Route::match(['post'], 'login', [Authenticate::class, 'login'])->middleware(['guest'])->name('login');

        Route::match(['get', 'head'], 'change-password', [ChangePassword::class, 'viewChangePassword'])->middleware(['auth', 'verified:web.account.notverified'])->name('change-password');

        Route::match(['put'], 'change-password', [ChangePassword::class, 'update'])->middleware(['auth', 'verified:web.account.notverified'])->name('change-password');

        Route::match(['get', 'head'], 'logout', [Authenticate::class, 'logout'])->middleware(['auth', 'verified:web.account.notverified'])->name('logout');

        Route::match(['get', 'head'], 'not-verified', function () {
            AuthenticationHelper::logout();

            return redirect()->route('web.account.login')->withErrors([
                'errorMessage' => 'You must verify your account.',
            ]);
        })->middleware([])->name('notverified');
    });

    Route::fallback(function () {
        return response()->view('errors.404');
    });
});

app/Models/Todo.php
<?php

namespace App\Models;

use App\Enums\TodoState;
use App\Traits\GenerateSlug;
use App\Traits\GenerateUuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Todo extends Model
{
    use GenerateSlug, GenerateUuid, HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'state',
        'is_private',
        'name',
        'description',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'id',
        'user_id',
        'deleted_at',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'state' => TodoState::class, // requires PHP 8.1+
        'is_private' => 'boolean',
        'checkmark_at' => 'datetime',
    ];

    /**
     * Get the user owner.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Dash/Dashboard.php
<?php

namespace App\Http\Controllers\Dash;

use App\Enums\TodoState;
use App\Http\Controllers\Controller;
use App\Models\Todo;

class Dashboard extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): \Illuminate\Http\Response
    {
        $todos = Todo::query()->whereIsPrivate(false)->whereState(TodoState::PUBLISH)->cursorPaginate();

        return response()->view('dash.dashboard', compact('todos'));
    }
}

app/Http/Controllers/Dash/Todo.php
<?php

namespace App\Http\Controllers\Dash;

use App\Enums\TodoState;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dash\StoreTodoRequest;
use App\Http\Requests\Dash\UpdateTodoRequest;
use App\Models\Todo as TodoModel;
use App\Models\User;

class Todo extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): \Illuminate\Http\Response
    {
        $todos = TodoModel::query()->whereUserId(auth()->user()->id)->cursorPaginate();

        return response()->view('dash.todos.index', compact('todos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): \Illuminate\Http\Response
    {
        $todoState = TodoState::cases();

        return response()->view('dash.todos.create', compact('todoState'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreTodoRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreTodoRequest $request): \Illuminate\Http\RedirectResponse
    {
        $todo = User::find($request->user()->id);

        $todo->todos()->create($request->only([
            'name',
            'description',
            'is_private',
            'state',
        ]));

        return redirect()->back()->with(['successMessage' => 'Todo has been created.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id): \Illuminate\Http\Response
    {
        $todo = TodoModel::query()->whereUserId(auth()->user()->id)->whereUuid($id)->firstOrFail();

        return response()->view('dash.todos.show', compact('todo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id): \Illuminate\Http\Response
    {
        $todo = TodoModel::query()->whereUserId(auth()->user()->id)->whereUuid($id)->firstOrFail();

        $todoState = TodoState::cases();

        return response()->view('dash.todos.edit', compact('todo', 'todoState'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateTodoRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateTodoRequest $request, $id): \Illuminate\Http\RedirectResponse
    {
        $todo = TodoModel::query()->whereUserId($request->user()->id)->whereUuid($id)->firstOrFail();

        $todo->update($request->only([
            'name',
            'description',
            'is_private',
            'state',
        ]));

        return redirect()->back()->with(['successMessage' => 'Todo has been updated.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id): \Illuminate\Http\RedirectResponse
    {
        $todo = TodoModel::query()->whereUserId(auth()->user()->id)->whereUuid($id)->firstOrFail();

        $todo->delete();

        return redirect()->back()->with(['successMessage' => 'Todo has been deleted.']);
    }
}

resources/views/dash/todos/create.blade.php
@extends('templates.app')

@section('title', 'Create Todo')

@section('content')
    <form action="{{ route('web.todos.store') }}" method="POST"
        class="mx-auto space-y-8 divide-y divide-gray-200 max-w-7xl sm:px-6 lg:px-8">
        @csrf
        <div class="grid grid-cols-1 mt-6 gap-y-6 gap-x-4 sm:grid-cols-6">
            <div
                class="px-3 py-2 max-w-sm border {{ $errors->has('name') ? 'border-red-500' : 'border-gray-300' }} rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
                <label for="name" class="block text-xs font-medium text-gray-900">
                    Name
                </label>
                <div class="mt-1">
                    <input type="text" name="name" id="name" value="{{ old('name') }}" autocomplete="on" required
                        class="block w-full p-0 text-gray-900 placeholder-gray-500 border-0 focus:ring-0 sm:text-sm">
                </div>
                @error('name')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

            <div
                class="overflow-hidden px-3 py-2 max-w-7xl border {{ $errors->has('description') ? 'border-red-500' : 'border-gray-300' }} rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
                <label for="description" class="block text-xs font-medium text-gray-900">
                    Description
                </label>
                <div class="mt-1">
                    <textarea rows="4" name="description" id="description"
                        class="block w-full p-0 text-gray-900 placeholder-gray-500 border-0 resize-none focus:ring-0 sm:text-sm">{{ old('description') }}</textarea>
                </div>
                @error('description')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

            <div class="max-w-sm px-3 py-2 border-none sm:col-span-3">
                <fieldset class="space-y-0">
                    <legend class="sr-only">Make Private</legend>
                    <div class="relative flex items-start">
                        <div class="flex items-center h-5">
                            <input id="is_private" name="is_private" value="1" type="checkbox"
                                class="w-4 h-4 text-green-400 border-gray-300 rounded cursor-pointer focus:ring-green-300"
                                @checked(old('is_private'))>
                        </div>
                        <div class="ml-3 text-sm">
                            <label for="is_private" class="font-medium text-gray-700 cursor-pointer">Private</label>
                        </div>
                        @error('is_private')
                            <div class="mt-1">
                                <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                                    {{ $message }}
                                </span>
                            </div>
                        @enderror
                    </div>
                </fieldset>
            </div>

            <div class="max-w-sm px-3 py-2 border-none sm:col-span-3">
                <select name="state" id="state"
                    class="block w-full text-sm text-gray-700 transition ease-in-out bg-white bg-no-repeat border border-gray-300 border-solid rounded-md appearance-none cursor-pointer form-select font-sm bg-clip-padding focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
                    <option selected>Status</option>
                    @if (count($todoState))
                        @foreach ($todoState as $state)
                            <option value="{{ $state->value }}" @selected(old('state') === $state->value)>{{ $state->value }}</option>
                        @endforeach
                    @endif
                </select>
                @error('state')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

        </div>

        <div class="py-4">
            <div class="flex justify-end" x-data="">
                <button x-on:click="location.href = '{{ route('web.todos.index') }}'" type="button"
                    class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Cancel
                </button>
                <button type="submit"
                    class="inline-flex justify-center px-4 py-2 ml-3 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Create
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/dash/todos/edit.blade.php
@extends('templates.app')

@section('title', 'Edit Todo: ' . $todo->name ?? null)

@section('content')
    <form action="{{ route('web.todos.update', ['id' => $todo->uuid]) }}" method="POST"
        class="mx-auto space-y-8 divide-y divide-gray-200 max-w-7xl sm:px-6 lg:px-8">
        @csrf
        @method('put')
        <div class="grid grid-cols-1 mt-6 gap-y-6 gap-x-4 sm:grid-cols-6">
            <div
                class="px-3 py-2 max-w-sm border {{ $errors->has('name') ? 'border-red-500' : 'border-gray-300' }} rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
                <label for="name" class="block text-xs font-medium text-gray-900">
                    Name
                </label>
                <div class="mt-1">
                    <input type="text" name="name" id="name" value="{{ $todo->name }}" autocomplete="on" required
                        class="block w-full p-0 text-gray-900 placeholder-gray-500 border-0 focus:ring-0 sm:text-sm">
                </div>
                @error('name')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

            <div
                class="overflow-hidden px-3 py-2 max-w-7xl border {{ $errors->has('description') ? 'border-red-500' : 'border-gray-300' }} rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
                <label for="description" class="block text-xs font-medium text-gray-900">
                    Description
                </label>
                <div class="mt-1">
                    <textarea rows="4" name="description" id="description"
                        class="block w-full p-0 text-gray-900 placeholder-gray-500 border-0 resize-none focus:ring-0 sm:text-sm">{{ $todo->description }}</textarea>
                </div>
                @error('description')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

            <div class="max-w-sm px-3 py-2 border-none sm:col-span-3">
                <fieldset class="space-y-0">
                    <legend class="sr-only">Make Private</legend>
                    <div class="relative flex items-start">
                        <div class="flex items-center h-5">
                            <input id="is_private" name="is_private" value="1" type="checkbox"
                                class="w-4 h-4 text-green-400 border-gray-300 rounded cursor-pointer focus:ring-green-300"
                                @checked($todo->is_private)>
                        </div>
                        <div class="ml-3 text-sm">
                            <label for="is_private" class="font-medium text-gray-700 cursor-pointer">Private</label>
                        </div>
                        @error('is_private')
                            <div class="mt-1">
                                <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                                    {{ $message }}
                                </span>
                            </div>
                        @enderror
                    </div>
                </fieldset>
            </div>

            <div class="max-w-sm px-3 py-2 border-none sm:col-span-3">
                <select name="state" id="state"
                    class="block w-full text-sm text-gray-700 transition ease-in-out bg-white bg-no-repeat border border-gray-300 border-solid rounded-md appearance-none cursor-pointer form-select font-sm bg-clip-padding focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">
                    <option selected>Status</option>
                    @if (count($todoState))
                        @foreach ($todoState as $state)
                            <option value="{{ $state->value }}" @selected($todo->state->value === $state->value)>{{ $state->value }}</option>
                        @endforeach
                    @endif
                </select>
                @error('state')
                    <div class="mt-1">
                        <span class="flex items-center mt-1 ml-1 text-xs font-medium tracking-wide text-red-500">
                            {{ $message }}
                        </span>
                    </div>
                @enderror
            </div>

        </div>

        <div class="py-4">
            <div class="flex justify-end" x-data="">
                <button x-on:click="location.href = '{{ route('web.todos.index') }}'" type="button"
                    class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Cancel
                </button>
                <button type="submit"
                    class="inline-flex justify-center px-4 py-2 ml-3 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Update
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/dash/todos/show.blade.php
@extends('templates.app')

@section('title', 'View Todo: ' . $todo->name ?? null)

@section('content')
    <div class="grid grid-cols-1 mt-6 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div
            class="max-w-sm px-3 py-2 border border-gray-300 rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
            <label for="name" class="block text-xs font-medium text-gray-900">
                Name
            </label>
            <div class="mt-1">
                <p class="text-sm">
                    {{ $todo->name }}
                </p>
            </div>
        </div>

        <div
            class="px-3 py-2 border border-gray-300 rounded-md shadow-sm max-w-7xl focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-6">
            <label for="description" class="block text-xs font-medium text-gray-900">
                Description
            </label>
            <div class="mt-1">
                <p class="text-sm">
                    {{ $todo->description }}
                </p>
            </div>
        </div>

        <div
            class="max-w-sm px-3 py-2 border border-gray-300 rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-3">
            <label for="is_private" class="block text-xs font-medium text-gray-900">
                Private?
            </label>
            <div class="mt-1">
                <p class="text-sm">
                    @if ($todo->is_private)
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="w-5 h-5 text-green-400">
                            <path fill-rule="evenodd"
                                d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12zm13.36-1.814a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z"
                                clip-rule="evenodd" />
                        </svg>
                    @else
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="w-5 h-5 text-red-900">
                            <path fill-rule="evenodd"
                                d="M12 2.25c-5.385 0-9.75 4.365-9.75 9.75s4.365 9.75 9.75 9.75 9.75-4.365 9.75-9.75S17.385 2.25 12 2.25zm3 10.5a.75.75 0 000-1.5H9a.75.75 0 000 1.5h6z"
                                clip-rule="evenodd" />
                        </svg>
                    @endif
                </p>
            </div>
        </div>

        <div
            class="max-w-sm px-3 py-2 border border-gray-300 rounded-md shadow-sm focus-within:ring-1 focus-within:ring-indigo-600 focus-within:border-indigo-600 sm:col-span-3">
            <label for="state" class="block text-xs font-medium text-gray-900">
                Status
            </label>
            <div class="mt-1">
                <p class="text-sm">
                    {{ $todo->state->value }}
                </p>
            </div>
        </div>

    </div>

    <div class="py-4">
        <div class="flex justify-end" x-data="">
            <button x-on:click="location.href = '{{ route('web.todos.index') }}'" type="button"
                class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Back
            </button>
        </div>
    </div>
@endsection